<?php

namespace App\Command;

use \App\Service\AdminService;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CreateAdminCommand extends Command
{
    //name of the command, used to create a user in console
    protected static $defaultName = 'app:create-admin';

    private $adminManager;

    public function __construct(AdminService $adminService)
    {
        $this->adminManager = $adminService;
        parent::__construct();
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this->setDescription('Create a new admin')->setHelp('This command allows your to create new admin');

        $this->addArgument('username', InputArgument::REQUIRED, 'The username of the admin');

        $this->addArgument('password', InputArgument::REQUIRED, 'Password');

        $this->addArgument('displayName', InputArgument::REQUIRED, 'Display name of the admin');
    }

    protected function execute(
        InputInterface $input,
        OutputInterface $output
    ) {


        $output->writeln(['Admin creator', '==============']);
        $output->writeln('Admin username: ' . $input->getArgument('username'));
        $output->writeln('Admin password: ' . $input->getArgument('password'));
        $output->writeln('Admin display name: ' . $input->getArgument('displayName'));


        $this->adminManager->createAdmin(['username' => $input->getArgument('username'), 'password' => $input->getArgument('password'), 'displayName' => $input->getArgument('displayName')]);

        $output->writeln('Admin created');


        parent::execute($input, $output); // TODO: Change the autogenerated stub

        return Command::SUCCESS;
    }
}